version: 2
updates:
  - assignees:
      - "tvogels01"
    directory: "/"
    open-pull-requests-limit: 3
    package-ecosystem: "pip"
    reviewers:
      - "data-engineering"
    schedule:
      day: "tuesday"
      interval: "weekly"
