# Simple workflow to run linters.

name: Lint Python code

on:
  push:
    paths:
    - ".github/workflows/lint.yaml"
    - "python/**"
    - "requirements-linters.txt"
    - "setup.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout out code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-linters.txt') }}
    - name: Install dependencies
      run: |-
        python3 -m pip install --upgrade pip
        python3 -m pip install --requirement requirements-linters.txt
    - name: Lint with black
      run: |-
        black --config ./etc/pyproject.toml --check python/ setup.py
    - name: Lint with isort
      run: |-
        isort --settings-path ./etc --check-only --recursive python/ setup.py
    - name: Lint with flake8
      run: |-
        flake8 python setup.py
  mypy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout out code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-linters.txt') }}
    - name: Install dependencies
      run: |-
        python3 -m pip install --upgrade pip
        python3 -m pip install --requirement requirements-linters.txt
    - name: Run type checker
      run: |-
        mypy python
